/*
 * CalculatorAPI
 *
 * CalculatorAPI
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace CalculatorApi.Models
{
    /// <summary>
    /// Calculator Request Model
    /// </summary>
    [DataContract]
    public partial class AutenticationRequest
    { 
        /// <summary>
        /// The authentication value (for example pelephone) of the user
        /// </summary>
        /// <value>The authentication value (for example pelephone) of the user</value>
        [Required]

        [DataMember(Name="authenticationValue")]
        public required string AuthenticationValue { get; set; }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

    }
}
